sudo: false
language: node_js
git:
  submodules: false
node_js:
- '10'
cache: yarn
branches:
  only:
  - master
before_deploy:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master

after_deploy:
  - sleep 30 # waiting for camp2019 gh-pages build
  - git config --global user.name "sitcon-tw-bot"
  - git config --global user.email "contact@sitcon.org"
  - git config --global push.default simple
  - git clone --depth 1 --branch gh-pages https://$GITHUB_TOKEN@github.com/sitcon-tw/camp
  - cd camp
  - git submodule init
  - git submodule update --remote
  - git commit -a -m "Update submodule 2019"
  - git push -f
